project/my_django_js_webapp/conf/urls.py
# conf/urls.py
from django.contrib import admin
from django.urls import path, include
from rawsound import urls as rawsound
from preprocessing import urls as preprocessing
from file_upload_examples import urls as file_upload_examples
from common.views import index
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('common/', include('common.urls')),
    path('admin/', admin.site.urls),
    path('kisti/', include('sound.urls')),
    path('preprocessing/', include((preprocessing, 'preprocessing'), namespace='preprocessing')),
    path('evaluation_set/', include('evaluation_set.urls')),
    path('rawsound/', include((rawsound, 'rawsound'), namespace='rawsound')),
    path('file_upload_examples/',include((file_upload_examples, 'file_upload_examples'), namespace='file_upload_examples')),
    path('api/', include('users.urls')),  #유저 부분 추가
]

urlpatterns += static('/excel/', document_root='media/upload/excel/')

project/my_django_js_webapp/rawsound/urls.py
from django.urls import path
from django.urls import include
from rest_framework.routers import DefaultRouter

from . import views as test
from .api import MetadataViewSet

router = DefaultRouter()
router.register(r'metadata', MetadataViewSet)

urlpatterns = [
    path('', include(router.urls)),
    
    # Metadata
    path('metadata_list/', test.metadata_list, name='metadata_list'),
    path('metadata_info/', test.metadata_info, name='metadata_form'),
    path('metadata_info/<int:data_set_idx>/', test.metadata_info, name='metadata_info'),
    path('create_metadata/', test.create_metadata, name='create_metadata'),
    path('update_metadata/<int:data_set_idx>/', test.update_metadata, name='update_metadata'),
    path('delete_metadata/<int:data_set_idx>/', test.delete_metadata, name='delete_metadata'),
    
    # Noise
    path('noise_info/<int:data_set_idx>/', test.noise_info, name='noise_info'),
    path('create_noise/<int:data_set_idx>/', test.create_noise, name='create_noise'),
    path('update_noise/<int:ni_set_idx>/', test.update_noise, name='update_noise'),
    path('delete_noise/<int:ni_set_idx>/', test.delete_noise, name='delete_noise'),
    
    
    # Detail
    path('detail_info/<int:data_set_idx>/', test.detail_info, name='detail_info'),
    path('create_detail/<int:data_set_idx>/', test.create_detail, name='create_detail'),
    path('update_detail/<int:snd_set_idx>/', test.update_detail, name='update_detail'),
    path('delete_detail/<int:snd_set_idx>/', test.delete_detail, name='delete_detail'),
]

project/my_django_js_webapp/rawsound/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.crypto import get_random_string
from sound.models import Detail, Metadata, Noise


# START: Sound Metadata
def metadata_list(request):
    context = {}

    all_metadata = Metadata.objects.all()
    context['all_metadata'] = all_metadata
    
    return render(request, 'metadata/metadata_list.html', context)


def metadata_info(request, data_set_idx=None):
    context = {}
    
    if data_set_idx:
        context['metadata'] = get_object_or_404(Metadata, data_set_idx=data_set_idx)
        context['noise_list'] = Noise.objects.filter(data_set_idx=data_set_idx)
    
    return render(request, 'metadata/metadata_info.html', context)
    

def create_metadata(request):
    Metadata.objects.create(
        data_set = request.POST.get('data_set'),
        version = request.POST.get('version'),
        media_url = request.POST.get('media_url'),
        ado_result = request.POST.get('ado_result'),
        bit_dep = int(request.POST.get('bit_dep')),
        rec_strime = request.POST.get('rec_strime'),
        tdms_flag = request.POST.get('tdms_flag'),
        reg_user = request.POST.get('reg_user'),
    )
    
    return redirect('rawsound:metadata_list')


def update_metadata(request, data_set_idx):
    target_metadata = get_object_or_404(Metadata, data_set_idx=data_set_idx)
    target_metadata.data_set = request.POST.get('data_set')
    target_metadata.version = request.POST.get('version')
    target_metadata.media_url = request.POST.get('media_url')
    target_metadata.ado_result = request.POST.get('ado_result')
    target_metadata.bit_dep = int(request.POST.get('bit_dep'))
    target_metadata.rec_strime = request.POST.get('rec_strime')
    target_metadata.tdms_flag = request.POST.get('tdms_flag')
    target_metadata.reg_user = request.POST.get('reg_user')
    target_metadata.save()
    
    return redirect(reverse('rawsound:metadata_info', args=[data_set_idx]))


def delete_metadata(request, data_set_idx):
    target_metadata = get_object_or_404(Metadata, data_set_idx=data_set_idx)
    target_metadata.delete()
    
    return redirect('rawsound:metadata_list')
# END: Sound Metadata



# START: Sound Noise
def noise_info(request, data_set_idx):
    context = {}
    
    context['metadata'] = get_object_or_404(Metadata, data_set_idx=data_set_idx)
    
    noise_list = Noise.objects.filter(data_set_idx=data_set_idx)
    context['noise_list'] = noise_list
    
    return render(request, 'metadata/noise_info.html', context)


def create_noise(request, data_set_idx):
    Noise.objects.create(
        data_set_idx = get_object_or_404(Metadata, data_set_idx=data_set_idx),
        ni_info = request.POST.get('ni_info'),
        ni_bg_cate = request.POST.get('ni_bg_cate'),
        ni_bg_sub_cate = request.POST.get('ni_bg_sub_cate'),
        ni_place = request.POST.get('ni_place'),
        ni_bg_sdb = request.POST.get('ni_bg_sdb'),
        ni_bg_luf = request.POST.get('ni_bg_luf'),
        ni_device = request.POST.get('ni_device'),
        ni_len = int(request.POST.get('ni_len')),
    )
    
    return redirect(reverse('rawsound:noise_info', args=[data_set_idx]))


def update_noise(request, ni_set_idx):
    target_noise = get_object_or_404(Noise, ni_set_idx=ni_set_idx)
    target_noise.ni_info = request.POST.get('ni_info')
    target_noise.ni_bg_cate = request.POST.get('ni_bg_cate')
    target_noise.ni_bg_sub_cate = request.POST.get('ni_bg_sub_cate')
    target_noise.ni_place = request.POST.get('ni_place')
    target_noise.ni_bg_sdb = request.POST.get('ni_bg_sdb')
    target_noise.ni_bg_luf = request.POST.get('ni_bg_luf')
    target_noise.ni_device = request.POST.get('ni_device')
    target_noise.ni_len = int(request.POST.get('ni_len'))
    target_noise.save()
    
    data_set_idx = target_noise.data_set_idx.data_set_idx
    
    return redirect(reverse('rawsound:noise_info', args=[data_set_idx]))


def delete_noise(request, ni_set_idx):
    target_noise = get_object_or_404(Noise, ni_set_idx=ni_set_idx)
    data_set_idx = target_noise.data_set_idx.data_set_idx
    target_noise.delete()
    
    return redirect(reverse('rawsound:noise_info', args=[data_set_idx]))
# END: Sound Noise



# START: Sound Detail
def detail_info(request, data_set_idx):
    context = {}
    
    context['metadata'] = get_object_or_404(Metadata, data_set_idx=data_set_idx)
    
    detail_list = Detail.objects.filter(data_set_idx=data_set_idx)
    context['detail_list'] = detail_list
    
    return render(request, 'metadata/detail_info.html', context)


def create_detail(request, data_set_idx):
    Detail.objects.create(
        data_set_idx = get_object_or_404(Metadata, data_set_idx=data_set_idx),
        snd_info = request.POST.get('snd_info'),
        snd_cate = request.POST.get('snd_cate'),
        snd_sub_cate = request.POST.get('snd_sub_cate'),
        snd_cmnt = request.POST.get('snd_cmnt'),
        snd_place = request.POST.get('snd_place'),
        snd_ni_db = request.POST.get('snd_ni_db'),
        snd_ni_luf = request.POST.get('snd_ni_luf'),
        snd_srt_time = request.POST.get('snd_srt_time'),
        snd_end_time = request.POST.get('snd_end_time'),
        snd_device = request.POST.get('snd_device'),
    )
    
    return redirect(reverse('rawsound:detail_info', args=[data_set_idx]))


def update_detail(request, snd_set_idx):
    target_detail = get_object_or_404(Detail, snd_set_idx=snd_set_idx)
    target_detail.snd_info = request.POST.get('snd_info')
    target_detail.snd_cate = request.POST.get('snd_cate')
    target_detail.snd_sub_cate = request.POST.get('snd_sub_cate')
    target_detail.snd_cmnt = request.POST.get('snd_cmnt')
    target_detail.snd_place = request.POST.get('snd_place')
    target_detail.snd_ni_db = request.POST.get('snd_ni_db')
    target_detail.snd_ni_luf = request.POST.get('snd_ni_luf')
    target_detail.snd_srt_time = request.POST.get('snd_srt_time')
    target_detail.snd_end_time = request.POST.get('snd_end_time')
    target_detail.snd_device = request.POST.get('snd_device')
    target_detail.save()
    
    data_set_idx = target_detail.data_set_idx.data_set_idx
    
    return redirect(reverse('rawsound:detail_info', args=[data_set_idx]))


def delete_detail(request, snd_set_idx):
    target_detail = get_object_or_404(Detail, snd_set_idx=snd_set_idx)
    data_set_idx = target_detail.data_set_idx.data_set_idx
    target_detail.delete()
    
    return redirect(reverse('rawsound:detail_info', args=[data_set_idx]))
# END: Sound Detail



def generate_random_metadata():
    data_set = get_random_string(10)
    version = "version 240927"
    media_url = f"Test URL rawsound {get_random_string(5)}"
    ado_result = "test"
    bit_dep = 20240927
    rec_strime = "test"
    tdms_flag = "test"
    reg_user = "test"

    Metadata.objects.create(
        data_set=data_set,
        version=version,
        media_url=media_url,
        ado_result=ado_result,
        bit_dep=bit_dep,
        rec_strime=rec_strime,
        tdms_flag=tdms_flag,
        reg_user=reg_user,
    )

project/my_django_js_webapp/rawsound/templates/metadata/detail_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <style>
        .form-group {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }
        form label {
            width: 120px;
            font-size: 16px;
            text-align: right;
            margin-right: 10px;
        }
        form input {
            font-size: 16px;
            margin-bottom: 10px;
            width: 250px;
        }
        form button {
            font-size: 16px;
            display: block;
            margin-top: 20px;
        }
    </style>

    <script>
        function setAction(button) {
            const form = button.closest('form');
            form.action = button.value;
        }
    </script>

</head>
    <body>
        <h1>Metadata No.{{metadata.data_set_idx}} Detail Info</h1>
        <h3>새 디테일 입력</h3>
        <form id="create-form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="snd_info">snd_info</label>
                <input type="text" name="snd_info" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_cate">snd_cate</label>
                <input type="text" name="snd_cate" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_sub_cate">snd_sub_cate</label>
                <input type="text" name="snd_sub_cate" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_cmnt">snd_cmnt</label>
                <input type="text" name="snd_cmnt" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_place">snd_place</label>
                <input type="text" name="snd_place" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_ni_db">snd_ni_db</label>
                <input type="text" name="snd_ni_db" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_ni_luf">snd_ni_luf</label>
                <input type="text" name="snd_ni_luf" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_srt_time">snd_srt_time</label>
                <input type="text" name="snd_srt_time" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_end_time">snd_end_time</label>
                <input type="text" name="snd_end_time" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_device">snd_device</label>
                <input type="text" name="snd_device" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <button type="submit" name="action" value="{% url 'rawsound:create_detail' metadata.data_set_idx %}" onclick="setAction(this)">Create</button>
        </form>

        {% for detail in detail_list %}
        <form id="form-id-{{ detail.snd_set_idx }}" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <h3>Detail No.{{ detail.snd_set_idx }}</h3>
            <input type="hidden" name="snd_set_idx" value="{{ detail.snd_set_idx }}">
            <div class="form-group">
                <label for="snd_info">snd_info</label>
                <input type="text" name="snd_info" value="{{ detail.snd_info }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_cate">snd_cate</label>
                <input type="text" name="snd_cate" value="{{ detail.snd_cate }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_sub_cate">snd_sub_cate</label>
                <input type="text" name="snd_sub_cate" value="{{ detail.snd_sub_cate }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_cmnt">snd_cmnt</label>
                <input type="text" name="snd_cmnt" value="{{ detail.snd_cmnt }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_place">snd_place</label>
                <input type="text" name="snd_place" value="{{ detail.snd_place }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_ni_db">snd_ni_db</label>
                <input type="text" name="snd_ni_db" value="{{ detail.snd_ni_db }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_ni_luf">snd_ni_luf</label>
                <input type="text" name="snd_ni_luf" value="{{ detail.snd_ni_luf }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_srt_time">snd_srt_time</label>
                <input type="text" name="snd_srt_time" value="{{ detail.snd_srt_time }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_end_time">snd_end_time</label>
                <input type="text" name="snd_end_time" value="{{ detail.snd_end_time }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="snd_device">snd_device</label>
                <input type="text" name="snd_device" value="{{ detail.snd_device }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <button type="submit" name="action" value="{% url 'rawsound:update_detail' detail.snd_set_idx %}" onclick="setAction(this)">Update</button>
                <button type="submit" name="action" value="{% url 'rawsound:delete_detail' detail.snd_set_idx %}" onclick="setAction(this)">Delete</button>
            </div>
        </form>
        {% empty %}
        <p>Detail이 없습니다</p>
        {% endfor %}

        {% if metadata %}
        <a href="{% url 'rawsound:metadata_info' metadata.data_set_idx %}">Go back to metadata info</a>
        {% endif %}
        <div class="form-group">
            <a href="{% url 'rawsound:metadata_list' %}">Go back to metadata list</a>
        </div>
    </body>
</html>

project/my_django_js_webapp/rawsound/templates/metadata/metadata_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        .form-group {
            display: flex;
            align-items: center; /* 라벨과 입력 필드를 수직 가운데 정렬 */
            margin-bottom: 10px;
        }
        form label {
            width: 120px;
            font-size: 16px;
            text-align: right;
            margin-right: 10px;
        }
        form input {
            font-size: 16px;
            margin-bottom: 10px;
            width: 250px;
        }
        form button {
            font-size: 16px;
            display: block;
            margin-top: 20px;
        }
    </style>
    <script>
        function setAction(button) {
            document.getElementById('metadata-form').action = button.value;
        }
    </script>
</head>
    <body>
        {% if metadata %}
        <h1>Metadata No.{{metadata.data_set_idx}}</h1>
        {% else %}
        <h1>New Metadata Info</h1>
        {% endif %}
        <form id="metadata-form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}

            <h3>Metadata</h3>
            <div class="form-group">
                <label for="data_set">data_set</label>
                <input type="text" name="data_set" value="{{ metadata.data_set }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="version">version</label>
                <input type="text" name="version" value="{{ metadata.version }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="media_url">media_url</label>
                <input type="text" name="media_url" value="{{ metadata.media_url }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ado_result">ado_result</label>
                <input type="text" name="ado_result" value="{{ metadata.ado_result }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="bit_dep">bit_dep</label>
                <input type="number" name="bit_dep" value="{{ metadata.bit_dep }}" required minlength="1" placeholder="int(11)">
            </div>
            <div class="form-group">
                <label for="rec_strime">rec_strime</label>
                <input type="text" name="rec_strime" value="{{ metadata.rec_strime }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="tdms_flag">tdms_flag</label>
                <input type="text" name="tdms_flag" value="{{ metadata.tdms_flag }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="reg_user">reg_user</label>
                <input type="text" name="reg_user" value="{{ metadata.reg_user }}" required minlength="1" placeholder="varchar(150)">
            </div>

            {% if metadata %}
            <div class="form-group">
                <button type="submit" name="action" value="{% url 'rawsound:update_metadata' metadata.data_set_idx %}" onclick="setAction(this)">Update</button>
                <button type="submit" name="action" value="{% url 'rawsound:delete_metadata' metadata.data_set_idx %}" onclick="setAction(this)">Delete</button>
            </div>
            {% else %}
            <button type="submit" name="action" value="{% url 'rawsound:create_metadata' %}" onclick="setAction(this)">Create</button>
            {% endif %}
        </form>

        {% if metadata %}
        <div class="form-group">
            <a href="{% url 'rawsound:noise_info' metadata.data_set_idx %}">Show noise list</a>
        </div>
        <div class="form-group">
            <a href="{% url 'rawsound:detail_info' metadata.data_set_idx %}">Show detail list</a>
        </div>
        {% endif %}
        <div class="form-group">
            <a href="{% url 'rawsound:metadata_list' %}">Go back to metadata list</a>
        </div>
    </body>
</html>

project/my_django_js_webapp/rawsound/templates/metadata/metadata_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Metadata List</title>
    <style>
        table {
            width: -webkit-fill-available;
            border-collapse: collapse;
            margin: 10px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border: 1px solid #ddd;
        }
    </style>
</head>
    <body>
        <h1>Metadata List</h1>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Data set</th>
                        <th>Media url</th>
                    </tr>
                </thead>
                <tbody>
                    {% for metadata in all_metadata %}
                        <tr>
                            <td>{{ metadata.data_set_idx }}</td>
                            <td>
                                <a href="{% url 'rawsound:metadata_info' metadata.data_set_idx %}">
                                    {{ metadata.data_set }}
                                </a>
                            </td>
                            <td>{{ metadata.media_url }}</a></td>
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
        <div>
            <a href="{% url 'rawsound:metadata_form' %}">Create new metadata</a>
        </div>
    </body>
</html>

project/my_django_js_webapp/rawsound/templates/metadata/noise_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <style>
        .form-group {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }
        form label {
            width: 120px;
            font-size: 16px;
            text-align: right;
            margin-right: 10px;
        }
        form input {
            font-size: 16px;
            margin-bottom: 10px;
            width: 250px;
        }
        form button {
            font-size: 16px;
            display: block;
            margin-top: 20px;
        }
    </style>

    <script>
        function setAction(button) {
            const form = button.closest('form');
            form.action = button.value;
        }
    </script>

</head>
    <body>
        <h1>Metadata No.{{metadata.data_set_idx}} Noise Info</h1>
        <h3>새 노이즈 입력</h3>
        <form id="create-form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="ni_info">ni_info</label>
                <input type="text" name="ni_info" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_bg_cate">ni_bg_cate</label>
                <input type="text" name="ni_bg_cate" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_bg_sub_cate">ni_bg_sub_cate</label>
                <input type="text" name="ni_bg_sub_cate" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_place">ni_place</label>
                <input type="text" name="ni_place" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_bg_sdb">ni_bg_sdb</label>
                <input type="text" name="ni_bg_sdb" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_bg_luf">ni_bg_luf</label>
                <input type="text" name="ni_bg_luf" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_device">ni_device</label>
                <input type="text" name="ni_device" value="" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_len">ni_len</label>
                <input type="number" name="ni_len" value="" required minlength="1" placeholder="Number">
            </div>
            <button type="submit" name="action" value="{% url 'rawsound:create_noise' metadata.data_set_idx %}" onclick="setAction(this)">Create</button>
        </form>

        {% for noise in noise_list %}
        <form id="form-id-{{ noise.ni_set_idx }}" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <h3>Noise No.{{ noise.ni_set_idx }}</h3>
            <input type="hidden" name="ni_set_idx" value="{{ noise.ni_set_idx }}">
            <div class="form-group">
                <label for="ni_info">ni_info</label>
                <input type="text" name="ni_info" value="{{ noise.ni_info }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_bg_cate">ni_bg_cate</label>
                <input type="text" name="ni_bg_cate" value="{{ noise.ni_bg_cate }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_bg_sub_cate">ni_bg_sub_cate</label>
                <input type="text" name="ni_bg_sub_cate" value="{{ noise.ni_bg_sub_cate }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_place">ni_place</label>
                <input type="text" name="ni_place" value="{{ noise.ni_place }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_bg_sdb">ni_bg_sdb</label>
                <input type="text" name="ni_bg_sdb" value="{{ noise.ni_bg_sdb }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_bg_luf">ni_bg_luf</label>
                <input type="text" name="ni_bg_luf" value="{{ noise.ni_bg_luf }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_device">ni_device</label>
                <input type="text" name="ni_device" value="{{ noise.ni_device }}" required minlength="1" placeholder="varchar(150)">
            </div>
            <div class="form-group">
                <label for="ni_len">ni_len</label>
                <input type="number" name="ni_len" value="{{ noise.ni_len }}" required minlength="1" placeholder="Number">
            </div>

            <div class="form-group">
                <button type="submit" name="action" value="{% url 'rawsound:update_noise' noise.ni_set_idx %}" onclick="setAction(this)">Update</button>
                <button type="submit" name="action" value="{% url 'rawsound:delete_noise' noise.ni_set_idx %}" onclick="setAction(this)">Delete</button>
            </div>
        </form>
        {% empty %}
        <p>Noise가 없습니다</p>
        {% endfor %}

        {% if metadata %}
        <a href="{% url 'rawsound:metadata_info' metadata.data_set_idx %}">Go back to metadata info</a>
        {% endif %}
        <div class="form-group">
            <a href="{% url 'rawsound:metadata_list' %}">Go back to metadata list</a>
        </div>
    </body>
</html>