project/my_django_js_webapp/conf/urls.py
# conf/urls.py
from django.contrib import admin
from django.urls import path, include
from rawsound import urls as rawsound
from preprocessing import urls as preprocessing
from file_upload_examples import urls as file_upload_examples
from common.views import index
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('common/', include('common.urls')),
    path('admin/', admin.site.urls),
    path('kisti/', include('sound.urls')),
    path('preprocessing/', include((preprocessing, 'preprocessing'), namespace='preprocessing')),
    path('evaluation_set/', include('evaluation_set.urls')),
    path('rawsound/', include((rawsound, 'rawsound'), namespace='rawsound')),
    path('file_upload_examples/',include((file_upload_examples, 'file_upload_examples'), namespace='file_upload_examples')),
    path('api/', include('users.urls')),  #유저 부분 추가
]

urlpatterns += static('/excel/', document_root='media/upload/excel/')

project/my_django_js_webapp/preprocessing/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from sound.api import MetadataViewSet, DetaildataViewSet
from .views import *
# from .views import post_list, post_detail
router = DefaultRouter()
router.register(r'meta', MetadataViewSet)
#router.register(r'detail', DetaildataViewSet)
#router.register(r'noise', NoisedataViewSet)

urlpatterns = [
    
    path('', include(router.urls)),
    path('preprocessing_list_page/', preprocessing_list_page, name='preprocessing_list_page'),
    path('get_preprocessing_list/', get_preprocessing_list, name='get_preprocessing_list'),
    path('preprocessing/', preprocessing, name='preprocessing'),
    path('preprocessing_delete/', preprocessing_delete, name='preprocessing_delete'),
    path('get_origin_source_list/', get_origin_source_list, name='get_origin_source_list'),
    path('confirm_library_active/', confirm_library_active, name='confirm_library_active'),
    
    #waveSurfer Audio
    path('show_audio_wave/', show_audio_wave, name='show_audio_wave'),
    
    # TEST
    path('meta_intro/', meta_intro, name='meta_intro'),
    path('meta_list/', meta_list, name='meta_list'),
    path('meta_list/<int:data_set_idx>/', meta_detail, name='meta_detail'),
    path('meta_list/meta_insert_page/', meta_insert_page, name='meta_insert_page'),
    path('meta_list/meta_insert/', meta_insert, name='meta_insert'),
    path('meta_list/<int:data_set_idx>/update_page/', meta_update_page, name='meta_update_page'),
    path('meta_list/<int:data_set_idx>/update/', meta_update, name='meta_update'),
    path('meta_list/<int:data_set_idx>/delete/', meta_delete, name='meta_delete'),
    
    path('noise/<int:meta_data_idx>/noise_list/', noise_list , name='noise_list'),
    path('noise/<int:meta_data_idx>/noise_insert_page/', noise_insert_page , name='noise_insert_page'),
    path('noise/noise_insert/', noise_insert , name='noise_insert'),
    path('noise/noise_detail/', noise_detail , name='noise_detail'),
    path('noise/<int:ni_set_idx>/noise_update_page/', noise_update_page , name='noise_update_page'),
    path('noise/noise_update/', noise_update , name='noise_update'),
    path('noise/<int:ni_set_idx>/noise_delete/', noise_delete , name='noise_delete'),
    
    path('sound_detail/<int:meta_data_idx>/sound_detail_list/', sound_detail_list , name='sound_detail_list'),
    path('sound_detail/<int:meta_data_idx>/sound_detail_insert_page/', sound_detail_insert_page , name='sound_detail_insert_page'),
    path('sound_detail_insert/', sound_detail_insert, name='sound_detail_insert'),
    path('sound_detail/<int:meta_data_idx>/sound_detail' , sound_detail, name='sound_detail'),
    path('sound_detail/<int:meta_data_idx>/sound_detail_update_page' , sound_detail_update_page, name='sound_detail_update_page'),
    path('sound_detail/sound_detail_update' , sound_detail_update, name='sound_detail_update'),
    path('sound_detail/sound_detail_delete' , sound_detail_delete, name='sound_detail_delete'),

]

project/my_django_js_webapp/preprocessing/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.urls import reverse
from django.http import HttpResponse, JsonResponse, FileResponse
from sound.models import Metadata, Noise, Detail

from django.forms.models import model_to_dict
from django.db import transaction, connection
from django.db.models import Q, F, CharField, Func, Value
from django.db.models.functions import Cast, Coalesce
from django.db.models.expressions import RawSQL

from .model_form import MetadataForm, NoiseForm, DetailForm
from django.contrib import messages

### 전처리 관련 라이브러리
from common.utils.file_error_checker import file_error_checker
from common.utils.data_process import data_process
from django.conf import settings
import datetime
import traceback
import json
import logging
import os
import uuid

log = logging.getLogger(__name__)

def preprocessing_list_page(request):
    context = {}
    return render(request,'preprocessing/preprocessing_list.html', context)


# 전처리 목록 가져오기
def get_preprocessing_list(request):
    context = {}
    try:
        orm_list_obj = Metadata.objects.all().annotate(
            snd_set_idx = F('detail__snd_set_idx'),
            snd_cate = F('detail__snd_cate'),
            snd_sub_cate = F('detail__snd_sub_cate'),
            snd_ni_db = F('detail__snd_ni_db'),
            snd_cmnt = F('detail__snd_cmnt')
        ).values(
            'snd_set_idx',
            'media_url',
            'reg_dt',
            'snd_cate',
            'snd_sub_cate',
            'version', # 이상치 값 대용 (임시)
            'lp_data_len', # 파일 길이 값 대용
            'snd_ni_db', # dB 값 대용
            'snd_cmnt' # 상태 값 대용
        )
        result_list = list(orm_list_obj)
        
        for item in result_list:
            for key, value in item.items():
                item[key] = value if value is not None else '-'
                
        context['data'] = result_list 
        return JsonResponse(context)
    except Exception as e :
        trace_back = traceback.format_exc()
        log.info(trace_back)
        context['msg'] = trace_back
        return JsonResponse(context)  
    
# 전처리 대상 리스트(원천 데이터) 가져오기
def get_origin_source_list(request):
    context = {}
    try:
        orm_list_obj = Metadata.objects.all().annotate(
            snd_cate = F('detail__snd_cate'),
            snd_sub_cate = F('detail__snd_sub_cate'),
            snd_place=RawSQL(
                "SELECT GROUP_CONCAT(snd_place SEPARATOR '/ ') FROM sound_detail WHERE data_set_idx = sound_metadata.data_set_idx", 
                ()
            )
        ).values(
            'data_set_idx',
            'media_url',
            'reg_dt',
            'snd_cate',
            'snd_sub_cate',
            'video_path',
            'snd_place',
            'version'
        ).order_by('data_set_idx')
        result_list = list(orm_list_obj)
        
        for item in result_list:
            for key, value in item.items():
                item[key] = value if value is not None else '-'
        
        log.debug('result_list >>> %s', result_list)
        log.debug('result_list query >>> %s', orm_list_obj.query)
        context['data'] = result_list 
        return JsonResponse(context)
    except Exception as e :
        trace_back = traceback.format_exc()
        log.info(trace_back)
        context['msg'] = trace_back
        return JsonResponse(context)  

# 검증 확인
def confirm_library_active(request):
    context = {}
    try:
        upload_path = settings.UPLOAD_URL 
        id_list = json.loads(request.body)
        print("upload_path >>>" , upload_path)
        print("id_list >>>" , id_list)
        with transaction.atomic():
            meta_objs = Metadata.objects.filter(data_set_idx__in=id_list)
            for obj in meta_objs:
                # media_url 확인
                file_path = upload_path + obj.media_url
                print('file_path >>>', file_path)
                result = file_error_checker(file_path)
                print('file_error_checker >>>', result)
                if result[0] == 'E000':
                    obj.version = '완료'
                else :
                    obj.version = ','.join(result)
                print('obj.version >>>',obj.version)
                
            Metadata.objects.bulk_update(meta_objs, ['version'])
        
        context['success'] = True
        return JsonResponse(context)
    
    except Exception as e :
        trace_back = traceback.format_exc()
        log.info(trace_back)
        context['msg'] = trace_back
        return JsonResponse(context) 
    

# waveSurfer
def show_audio_wave(request):
    context = {}
    try :
        meta_data_id = request.GET.get('id')
        upload_path = settings.UPLOAD_URL
        meta_objs = Metadata.objects.filter(data_set_idx=meta_data_id)
        meta_obj = None
        if meta_objs.exists():
            meta_obj = meta_objs[0]
        else :
            return JsonResponse({'error': 'Metadata not found'}, status=500)
        
        file_path = upload_path + '/' +meta_obj.media_url
        print("audio file_path >>>", file_path)
        if os.path.exists(file_path):
            return FileResponse(open(file_path,'rb'), content_type='audio/wav')
        else :
            return JsonResponse({'error': 'File not found'}, status=404)
    except Exception as e :
        trace_back = traceback.format_exc()
        log.info(trace_back)
        context['msg'] = '오디오 Wave 호출 에러'
        return JsonResponse(context,status=500)  

# 전처리 적용
def preprocessing(request):
    context = {}
    try:
        item_list = json.loads(request.body)
        result_list = []
        with transaction.atomic():
            for item in item_list: 
                print("item >>>",item)
                meta_data = Metadata.objects.filter(data_set_idx=item['id'])
                if meta_data.exists():
                    meta_obj = meta_data[0]
                else :
                    raise CustomMessageException('전처리 존재하지 않은 Metadata 인스턴스 에러')
                
                upload_path = settings.UPLOAD_URL
                src_path = upload_path + '/' +meta_obj.media_url
                file_name = meta_obj.media_url.replace(".wav", "")
                random_name = str(uuid.uuid4()).replace('-', '')[:6]
                dst_path = upload_path + '/' + file_name + '_' +random_name + '.wav'
                data_process(src_path, dst_path, slice={'start': item['start'], 'end': item['end']})
                file_info = {}
                file_info['origin_file_name'] = meta_obj.media_url
                file_info['preprocessing_file_name'] = file_name + '_' +random_name + '.wav'
                result_list.append(file_info)
                
        context['success'] = True
        context['msg'] = '전처리 완료'
        context['result_list'] = result_list 
        return JsonResponse(context)
    except CustomMessageException as e:
        trace_back = traceback.format_exc()
        print(trace_back)
        log.info(trace_back)
        context['msg'] = e.message
        return JsonResponse(context,status=500)  
    
    except Exception as e :
        trace_back = traceback.format_exc()
        log.info(trace_back)
        print(trace_back)
        context['msg'] = '전처리 에러'
        return JsonResponse(context,status=500)  


def preprocessing_delete(request):
    context = {}
    try:
        id_list = json.loads(request.body)
        with transaction.atomic():
            detail_objs = Detail.objects.filter(snd_set_idx__in=id_list)
            for obj in detail_objs:
                obj.snd_cmnt = '삭제'   
            Detail.objects.bulk_update(detail_objs, ['snd_cmnt'])
        
        context['success'] = True
        context['msg'] = '삭제 완료'
        return JsonResponse(context)
    
    except Exception as e :
        trace_back = traceback.format_exc()
        log.info(trace_back)
        context['msg'] = '삭제 에러'
        return JsonResponse(context,status=500)  

# Test Code
def meta_intro(request):
    context = {}
    return render(request,'sample/meta_data/meta_intro.html', context)

def meta_list(request):
    context = {}
    meta_result = Metadata.objects.all().values(
        'data_set_idx'
        ,'data_set'
        ,'version'
        ,'media_url'
        ,'cre_dt'
        ,'ado_result'
        ,'bit_dep'
        ,'sam_rte'
        ,'rec_strime'
        ,'tdms_flag'
        ,'file_path'
        ,'daq_sam_rte'
        ,'x_pixel'
        ,'y_pixel'
        ,'ip_cam_x_slop'
        ,'ip_cam_y_slop'
        ,'beam_wid'
        ,'beam_hei'
        ,'lp_data'
        ,'lp_data_idx'
        ,'lp_data_len'
        ,'lp_data_file_path'
        ,'img_data'
        ,'img_idx'
        ,'img_file_path'
        ,'beam_pwr'
        ,'beam_pwr_idx'
        ,'beam_pwr_path'
        ,'img_video_path'
        ,'beam_video_path'
        ,'video_path'
        ,'reg_user'
        ,'reg_dt'
    )
    context['meta_list'] = list(meta_result)
    return render(request,'sample/meta_data/meta_list.html', context)
    
def meta_detail(request, data_set_idx):
    context = {}
    meta_data = Metadata.objects.filter(data_set_idx=data_set_idx).values()
    if meta_data.exists():
        meta_data = meta_data[0]
    context['meta_data'] = dict(meta_data)
    return render(request,'sample/meta_data/meta_detail.html', context)

def meta_update_page(request, data_set_idx):
    context = {}
    meta_data = Metadata.objects.filter(data_set_idx=data_set_idx).values()
    if meta_data.exists():
        meta_data = meta_data[0]
    context['meta_data'] = dict(meta_data)
    return render(request,'sample/meta_data/meta_update_page.html', context)

def meta_insert_page(request):
    context = {}
    return render(request, 'sample/meta_data/meta_insert_page.html', context)

def meta_insert(request):
    context = {}
    try:
        data_dict = {
            'data_set': request.POST.get('data_set'),
            'media_url': request.POST.get('media_url'),

project/my_django_js_webapp/preprocessing/templates/sample/sound_detail/sound_detail_insert_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sound Detail Insert Page</title>
    <style>
        .btn {
            display: inline-block;
            padding: 10px 15px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            margin: 5px; /* 여백 추가 */
        }
        .btn_noise{
            display: inline-block;
            padding: 10px 15px;
            background-color: #FFA500;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            margin: 5px; /* 여백 추가 */
        }
        .btn-submit {
            background-color: #28a745; /* 제출 버튼 색상 */
        }
    </style>
    <script src="{% static 'preprocessing/js/jquery-3.7.1.min.js' %}"></script>
    <script>
        $(document).ready(function(){
            // { url 'noise_insert' }
            
            $("#s_detail_submit").on("click",function(){
                // 폼 데이터 수집
                let jsonData = form_to_json($("#sound_detail_insert"));
                console.log("s_detail insert jsonData >>>", jsonData)
                jsonData['data_set_idx'] = $("input[name='data_set_idx']").val();
                let csrftoken = jsonData['csrfmiddlewaretoken']
                delete jsonData['csrfmiddlewaretoken'];
                $.ajax({
                    url:"{% url 'preprocessing:sound_detail_insert' %}",
                    type : "POST",
                    data : JSON.stringify(jsonData),
                    contentType: "application/json",
                    beforeSend: function(xhr) {
                        // CSRF 토큰을 헤더에 추가
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success : function(response){
                        console.log("response >>>", response)
                        s_d_data = response.sound_detail_obj;
                        let redirectUrl = "{% url 'preprocessing:sound_detail' 0 %}"+"?snd_set_idx="+ s_d_data['snd_set_idx'];
                        redirectUrl = redirectUrl.replace('/0/','/'+ String(s_d_data['data_set_idx']) + '/')
                        location.href = redirectUrl;
                    },
                    error : function(response){
                        if(typeof response.responseJSON != "undefined"){
                            //console.log("Error Msg >>>",response.responseJSON.msg)
                            alert(response.responseJSON.msg)
                        }
                    }
                })
            });
            
        });

        function form_to_json(formNode){
            let jsonData = {}
            let formData = formNode.serializeArray();
            $.each(formData, function() {
                jsonData[this.name] = this.value;
            });
            return jsonData
        }

    </script>
</head>
<body>
    <h1>Sound Detail</h1>
    <form id="sound_detail_insert">
        {% csrf_token %}
        <table border="1">
            <tbody>
                <tr>
                    <th>데이터셋</th>
                    <td><input type="text" name="data_set_idx" value="{{ meta_data_idx }}" disabled />  </td>
                </tr>
                <tr>
                    <th>소리 상세정보 값</th>
                    <td><input type="text" name="snd_info" /></td>
                </tr>
                <tr>
                    <th>소리 카테고리</th>
                    <td><input type="text" name="snd_cate" /></td>
                </tr>
                <tr>
                    <th>소리 서브카테고리</th>
                    <td><input type="text" name="snd_sub_cate" /></td>
                </tr>
                <tr>
                    <th>소리 상세내용</th>
                    <td><input type="text" name="snd_cmnt" /></td>
                </tr>
                <tr>
                    <th>소리 녹취 장소</th>
                    <td><input type="text" name="snd_place" /></td>
                </tr>
                <tr>
                    <th>소리 최대 dB</th>
                    <td><input type="text" name="snd_ni_db" /></td>
                </tr>
                <tr>
                    <th>소리 LUFS</th>
                    <td><input type="text" name="snd_ni_luf" /></td>
                </tr>
                <tr>
                    <th>소리 시작 시간</th>
                    <td><input type="text" name="snd_srt_time" /></td>
                </tr>
                <tr>
                    <th>소리 종료 시간</th>
                    <td><input type="text" name="snd_end_time" /></td>
                </tr>
                <tr>
                    <th>소리 시간</th>
                    <td><input type="number" name="snd_len" /></td>
                </tr>
                <tr>
                    <th>소리 녹취장비</th>
                    <td><input type="text" name="snd_device" /></td>
                </tr>
                <tr>
                    <th>소리 위급 수준</th>
                    <td><input type="text" name="snd_danger" /></td>
                </tr>
            
            </tbody>
        </table>
        <br>
        <a href="{% url 'preprocessing:meta_detail' meta_data_idx %}" class="btn">메타데이터 상세</a>
        <a href="{% url 'preprocessing:meta_list' %}" class="btn">메타데이터 리스트</a>
        <a href="{% url 'preprocessing:noise_list' meta_data_idx %}" class="btn_noise">배경소리 리스트</a>
        <button id="s_detail_submit" type="button" class="btn btn-submit">제출</button>
    </form>
</body>
</html>

project/my_django_js_webapp/preprocessing/templates/sample/sound_detail/sound_detail_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sound Detail List</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }

        .btn {
            display: inline-block;
            padding: 10px 15px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            margin: 5px; /* 여백 추가 */
        }
        .btn_noise{
            display: inline-block;
            padding: 10px 15px;
            background-color: #FFA500;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            margin: 5px; /* 여백 추가 */
        }
        .btn_detail{
            display: inline-block;
            padding: 10px 15px;
            background-color: #008000;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            margin: 5px; /* 여백 추가 */
        }
        .btn-submit {
            background-color: #28a745; /* 제출 버튼 색상 */
        }

    </style>
    <script src="{% static 'preprocessing/js/jquery-3.7.1.min.js' %}"></script>
    <script>
        $(document).ready(function(){
            $("a[name='sound_detail_delete']").on("click",function(){
                let r_data = {};
                r_data['snd_set_idx'] = $(this).closest('tr').find("input[name='snd_set_idx']").val();
                r_data['data_set_idx'] = $(this).closest('tr').find("input[name='data_set_idx']").val();
                
                $.ajax({
                    url : "{% url 'preprocessing:sound_detail_delete' %}",
                    type : "POST",
                    data : JSON.stringify(r_data),
                    contentType: "application/json",
                    beforeSend: function(xhr) {
                        // CSRF 토큰을 헤더에 추가
                        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                    },
                    success : function(response){
                        alert(response["msg"]);
                        location.reload();
                    },
                    error : function(response){
                        if(typeof response.responseJSON != "undefined"){
                            alert(response.responseJSON.msg)
                            location.reload();
                        }
                    }
    
                });
            });
        });

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.startsWith(name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        
    </script>
</head>
<body>
    <h1>Sound Detail List</h1>
    <ul>
        <table>
            <thead>
                <tr>
                    <th>데이터 셋</th>
                    <th>소리 상세정보 값</th>
                    <th>소리 카테고리</th>
                    <th>소리 서브카테고리</th>
                    <th>소리 상세내용</th>

                    <th>소리 녹취 장소</th>
                    <th>소리 최대 dB</th>
                    <th>소리 LUFS</th>
                    <th>소리 시작 시간</th>
                    <th>소리 종료 시간</th>
                    
                    <th>소리 시간</th>
                    <th>소리 녹취장비</th>
                    <th>소리 위급 수준</th>
                    <th>보기</th>
                    <th>수정</th>
                    <th>삭제</th>
                </tr>
            </thead>
            <tbody>
                {% for s_detail in s_detail_list %}
                <tr>
                    <input type="hidden" name="snd_set_idx" value="{{ s_detail.snd_set_idx }}"/>
                    <input type="hidden" name="data_set_idx" value="{{ s_detail.data_set_idx }}"/>
                    <td>{{ s_detail.data_set_idx.data_set_idx }}</td>
                    <td>{{ s_detail.snd_info }}</td>
                    <td>{{ s_detail.snd_cate }}</td>
                    <td>{{ s_detail.snd_sub_cate }}</td>
                    <td>{{ s_detail.snd_cmnt }}</td>

                    <td>{{ s_detail.snd_place }}</td>
                    <td>{{ s_detail.snd_ni_db }}</td>
                    <td>{{ s_detail.snd_ni_luf }}</td>
                    <td>{{ s_detail.snd_srt_time }}</td>
                    <td>{{ s_detail.snd_end_time }}</td>

                    <td>{{ s_detail.snd_len }}</td>
                    <td>{{ s_detail.snd_device }}</td>
                    <td>{{ s_detail.snd_danger }}</td>

                    <td><a href="{% url 'preprocessing:sound_detail' meta_data_idx %}?snd_set_idx={{ s_detail.snd_set_idx }}" >보기</a></td>
                    <td><a href="{% url 'preprocessing:sound_detail_update_page' meta_data_idx %}?snd_set_idx={{ s_detail.snd_set_idx }}">수정</a></td>
                    <td><a name="sound_detail_delete" href="javascript:void(0);">삭제</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="16">No data available.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        <a href="{% url 'preprocessing:meta_detail' meta_data_idx %}" class="btn">메타데이터 상세</a>
        <a href="{% url 'preprocessing:meta_list' %}" class="btn">메타데이터 리스트</a>
        <a href="{% url 'preprocessing:meta_intro' %}" class="btn">메타데이터 인트로 화면</a>
        
        <a href="{% url 'preprocessing:sound_detail_insert_page' meta_data_idx %}" class="btn_noise">소리 입력</a>
        
    </ul>
</body>
</html>